### ISSUE TITLE
GetAssignment only returns first page of assignments

### ISSUE THREAD

**Issue by jegreen90** [cloudyr/pyMTurkR#3]
I have a HIT with 261 submitted assignments. When I use the GetAssignment function, it reads, "261 Assignments Retrieved". However, I can only view what I think is the first page of the assignments. As in, when I save the assignments as a dataframe in R, I only have 61 cases. I've tried the various options within the GetAssignment function (e.g., pagetoken) and nothing has worked.

mydata <- GetAssignment(hit = "[my hit]", status = "Submitted") 

^When I run this, the "mydata" dataframe only has 61 cases, rather than 261. 

In MTurkR, this problem was resolved by adding the option, "return.all = TRUE" into the command. However, this is not an argument now.
mydata <- GetAssignment(hit = "[my hit]", status = "Submitted", return.all = TRUE)

**Comment by tylerburleigh** [comment]
Can you try again using version >= 0.3.8?

**Comment by tylerburleigh** [comment]
I was able to reproduce the behavior you described with a HIT that had more than 100 assignments, and it seems to be working with the update.

**Comment by jegreen90** [comment]
Thanks, Tyler! It's working well. Problem resolved.

**Comment by jonwoon** [comment]
Hi @tylerburleigh . GetAssignment returns 100 assignments for me, even though I know the HIT has 150.

**Comment by joshua-a-becker** [comment]
I seem to be having this same problem, though now with version 1.1.5 (installed today)

my call "GetAssignment(hit=HITId, pagetoken = 1)" returns the same as "GetAssignment(hit=HITId, pagetoken = 2)"

(i have verified on the amazon web UI that this HIT has more than 100 assignments completed)

is there any workaround for this?
