### ISSUE TITLE
Issue approving workers

### ISSUE THREAD

**Issue by brentkaplan** [cloudyr/pyMTurkR#4]
Hi. Thanks so much for adapting and maintaining this package! You are doing awesome work. 

I tried to approve some assignments and getting an error:

```
> ApproveAssignment(assignments = hitassigns$AssignmentId,
+                   feedback = approvemsg)
Error in names(object) <- nm : 
  'names' attribute [4] must be the same length as the vector [3]
```

I believe because `ApproveAssignment` misspecifies the number of columns (3 instead of 4):
```
Assignments <- emptydf(length(assignments), 3, c("AssignmentId", 
        "Feedback", "OverrideRejection", "Valid"))
```

Should be:
```
Assignments <- emptydf(length(assignments), 4, c("AssignmentId", 
        "Feedback", "OverrideRejection", "Valid"))
```

**Comment by tylerburleigh** [comment]
Thanks @brentkaplan, great catch! 
I fixed this in the latest commit https://github.com/cloudyr/pyMTurkR/commit/a2e1e352c7a5502dda80b5f0041064674eaaccd2 (version 0.5.8).
