### ISSUE TITLE
GetAssignment returns duplicate assignments

### ISSUE THREAD

**Issue by jonwoon** [cloudyr/pyMTurkR#9]
Hi! I really appreciate having this package to use to access the MTurk API. 

`df <- GetAssignment(hit = "HITid")`

This returns a data frame with duplicate assignments: e.g., if the HIT has 9 assignments, the data frame has 18 rows with rows 1-9 duplicated in rows 10-18.

**Comment by tylerburleigh** [comment]
Hi @jonwoon are you using the version from CRAN or from this repo?

What is the output of `packageVersion("pyMTurkR")`?

**Comment by jonwoon** [comment]
It's 1.1, from CRAN.

**Comment by tylerburleigh** [comment]
@jonwoon please try updating to the latest development version:

`devtools::install_github("cloudyr/pyMTurkR")`

then verify with `packageVersion("pyMTurkR")` that you are running 1.14

**Comment by jonwoon** [comment]
It is fine in 1.14. Thanks!

**Comment by LukasWallrich** [comment]
Hi there, and thanks a lot for the ongoing development.

Unfortunately, I am having exactly the same issue in version 1.14 (possibly only while the HIT is still running). I have three completed assignments that are repeated twice.
